#+TITLE: Network security fundamentals

* Preserving security

Computer security is about *preserving* (not creating) security regarding information and its core security properties, known as *CIA triad*
#+BEGIN_QUOTE
The protection afforded to an automated information system in order to attain the applicable objectives of preserving the integrity, the availability and confidentiality of information systems resources.
#+END_QUOTE
- Confidentiality :: The information is accessible only by who is authorized
- Integrity :: The information is accurate and correct
- Availability :: The information can be reached when needed
Additional properties may be also be preserved
- Accountability :: Actions on the information are accountable to somebody/something
- Non-repudiation :: Actions on the information can't be refused by its author
- Authentication :: Of user, messages, etc.

Any computer security rieles on *TCBs* (trusted computing bases) built with trusted parts
- Trusted parts always include hardware, firmware and software
- If a trusted component is breached, the security properties of the entire system may be compromised
- Minimizing the size of the TCB is key to deal with security

* TODO "Reflection on Trusting Trust" by Ken Thompson [fn:1] [fn:2]
* Network security

The goal is still to preserve the CIA properties, threats may be for example
- Confidentiality :: Raeding packets by message spoofing
- Integrity :: Altering packets with message spoofing
- Availability :: DoS, router dropping all the packets

However, network securities adds even more challenges
- The (real) client-server communication :: A classic, high level client-server model often hides a complex reality where many intermediary points (routers, gateways, ISPs, DNSs) and responses coming from different parties.
- Etherogeneous protocols and technologies :: A wide range of protocols and technologies is adopted in networking (and computing in general). However, the joint points of this different architectures often hide *vulnerabilties*.
- Legacy issues :: The adoption of new versions of protocols is often slow, exposing many hosts to risk and lowering the security level
(e.g. IPv6 and IPv4)

* Footnotes

[fn:2] [[https://medium.com/computers-papers-and-everything/2-reflections-on-trusting-trust-1ba5709c2f27][Paper summary by Krisha Mehta, medium.com]]

[fn:1] [[http://users.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf][Reflections on Trusting Trust, Ken Thompson, 1984]]
